# Generated by Django 6.0.1 on 2026-02-01 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_depressionscan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('marital_status', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('pin_code', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('job', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('stress_reason', models.JSONField(blank=True, default=list)),
                ('father', models.CharField(blank=True, max_length=50, null=True)),
                ('mother', models.CharField(blank=True, max_length=50, null=True)),
                ('spouse', models.CharField(blank=True, max_length=50, null=True)),
                ('children', models.CharField(blank=True, max_length=100, null=True)),
                ('grandfather', models.CharField(blank=True, max_length=50, null=True)),
                ('grandmother', models.CharField(blank=True, max_length=50, null=True)),
                ('sister', models.CharField(blank=True, max_length=50, null=True)),
                ('brother', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
