# Generated by Django 6.0.1 on 2026-02-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_country_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinformation',
            name='marks',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
