# Generated by Django 6.0.1 on 2026-02-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='message',
            new_name='appointment_spec',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='mode',
            field=models.CharField(default='Audio', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default='Guest', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='set_by',
            field=models.CharField(default='Counselor', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
