# Generated by Django 4.2.11 on 2026-02-22 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsellor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counsellor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='counsellor_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
