# Generated by Django 4.2.11 on 2026-02-23 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_counsellor_created_at_counsellor_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='English', max_length=50)),
                ('theme', models.CharField(default='Light', max_length=20)),
                ('timezone', models.CharField(default='IST (UTC+5:30)', max_length=100)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=50)),
                ('counsellor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='api.counsellor')),
            ],
        ),
    ]
